jenkins:
  agentProtocols:
  - "Diagnostic-Ping"
  - "JNLP4-connect"
  - "OperationsCenter2"
  - "Ping"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: true
  numExecutors: 0
unclassified:
  globallibraries:
    libraries:
    - defaultVersion: "master"
      name: "kypseli"
      retriever:
        modernSCM:
          scm:
            github:
              credentialsId: "kypseli-github-token"
              id: "1218532a-b993-4a4c-976f-7c0d8871cbe3"
              repoOwner: "kypseli"
              repository: "pipeline-library"
              traits:
              - branchDiscoveryTrait:
                  strategyId: 1
              - originPullRequestDiscoveryTrait:
                  strategyId: 1
              - forkPullRequestDiscoveryTrait:
                  strategyId: 1